### ISSUE TITLE
Day tab titles should be based on cycle’s date

### ISSUE THREAD

**Issue by aaron25mt** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#27]
Right now, when you start a new cycle, the tabs all start on Monday. They should be dynamic based on when you created that cycle.

**Comment by JonnyBeeGod** [comment]
While this may lead to a correct behavior for some users, not everyone will add a new cycle the day he will begin the first day of the cycle. I'd rather have the naming of the days consistent with the spreadsheets instead of confusing users with (to them) seemingly arbitrary naming of the days in the cycle. I agree it would be an enhancement to let the user decide on which days he want to train but this should not be automated based on the date he created the cycle - maybe it should not be automated at all and be a manual process, I don't know yet. See also this issue: https://github.com/JonnyBeeGod/nSuns-5-3-1-iOS-issues/issues/9
Thanks for the input!
