### ISSUE TITLE
Progression in calculated incorrectly

### ISSUE THREAD

**Issue by firedev** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#69]
I put 3+ in all AMRAP progression sets. Progression settings are default. I did 3 reps for deadlift and it’s increased by 10lbs instead of 5lbs which is the default for 2-3 reps.

**Comment by JonnyBeeGod** [comment]
Cant reproduce on my build. Quite some time has passed since you reported it and I did some changes. If it still happens with the new release which will come in a few days, please reopen with more information: which template, whether you did modifications to the templates and maybe a screenshot. Thanks!
