### ISSUE TITLE
"Recommended Exercises" have disappeared

### ISSUE THREAD

**Issue by rr3021** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#74]
Under "Add Accessories", the "Recommended" text has disappeared. The previous time this occurred I fixed it by redownloading the app at the cost of losing previous progress. Both times running unaltered 5day progression.

**Screenshots**
<img width="375" alt="image" src="https://user-images.githubusercontent.com/24324872/53306417-dbf52900-385a-11e9-8759-115f115b0487.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 12.1.4 (Previous time occurred on a previous build of iOS 12)
 - App Version 1.10.1

**Comment by JonnyBeeGod** [comment]
Recommended accessories disappear when there are modifications done to the templates. Because the app can't figure out on its own how it should react to changes to the templates the easiest is for me to make the recommended accessories disappear. Since I got many complaints about that maybe it would be better instead of hiding the recommended accessories to display a disclaimer, that these are only valid for the originally unaltered templates

**Comment by joostmaes** [comment]
I have a suggestion for this. Maybe you can create a field in the template editor where you can manually override the text displayed per workout day. 

Example:
https://imgur.com/a/u5yApWx

**Comment by JonnyBeeGod** [comment]
closed because there is an open issue(#57 ) which fixes it
